baseURL = "https://shansrin.github.io/sample-docs-theme/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-techdoc"
publishDir = "../docs"

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1